"""Bundle website/data/*.json into a plain script.

    python tools/bundle-data.py

Browsers refuse fetch() on file:// URLs, so a page that loads its data with
fetch only works behind a web server. Assigning the same data to a global in
a <script> works everywhere — served over HTTP, or opened by double-clicking
the HTML. That turns the demo from "hope Python is installed" into "open the
folder and double-click".

The .json files stay the editable source. Re-run this after changing them.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "website" / "data"
OUT = DATA / "bundle.js"

SOURCES = {
    "sets": "periodontic-sets.json",
    "centres": "centres.json",
}

def main():
    payload = {}
    for key, filename in SOURCES.items():
        path = DATA / filename
        payload[key] = json.loads(path.read_text(encoding="utf-8"))
        print("%-26s %6.1f KB" % (filename, path.stat().st_size / 1024))

    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "/* Generated by tools/bundle-data.py — do not edit.\n"
        "   Edit the .json files in this folder and re-run the script.\n"
        "   Exists so the site runs from file:// as well as over HTTP. */\n"
        "window.MOH_DATA = " + body + ";\n",
        encoding="utf-8")
    print("%-26s %6.1f KB  <- bundle" % (OUT.name, OUT.stat().st_size / 1024))

if __name__ == "__main__":
    main()
