"""Download IBM Plex from Google Fonts and self-host it.

    python design-system/tools/fetch-fonts.py

Self-hosted rather than linked so the service works with no internet: a
ministry basement, a clinic with no wifi, a demo room whose network wants a
login. A page whose typography collapses to Times New Roman because the venue
has no network is not a page anyone wants to present.

All three families are SIL Open Font License, so redistributing the files is
explicitly permitted. Only the Latin and Arabic subsets are kept — the Greek,
Cyrillic, Vietnamese and Thai ones this service will never render are dropped,
which is about 400 KB saved.
"""
import os
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # design-system/
OUT = ROOT / "assets" / "fonts"
CSS_OUT = ROOT / "foundations" / "fonts.css"
KEEP_SUBSETS = ("latin", "latin-ext", "arabic")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36")
URL = ("https://fonts.googleapis.com/css2?"
       "family=IBM+Plex+Sans:wght@400;500;600;700"
       "&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700"
       "&family=IBM+Plex+Mono:wght@400;500&display=swap")

HEADER = """/* ==========================================================================
   foundations/fonts.css — IBM Plex, self-hosted.

   Generated by tools/fetch-fonts.py. Do not edit by hand; re-run the script.
   Latin and Arabic subsets only. SIL Open Font License.
   ========================================================================== */

"""


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    css = fetch(URL)

    blocks = re.findall(r"(/\*\s*([a-z\-]+)\s*\*/\s*)?@font-face\s*\{([^}]*)\}", css)
    faces, seen, total = [], set(), 0

    for _, subset, body in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        src = re.search(r"url\(([^)]+)\)\s*format\('woff2'\)", body)
        if not src:
            continue

        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        style = re.search(r"font-style:\s*(\w+)", body)
        urange = re.search(r"unicode-range:\s*([^;]+);", body)

        name = "%s-%s-%s.woff2" % (family.lower().replace(" ", "-"), weight, subset)
        if name in seen:
            continue
        seen.add(name)

        data = fetch(src.group(1), binary=True)
        (OUT / name).write_bytes(data)
        total += len(data)

        faces.append(
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            "  src: url('../assets/fonts/%s') format('woff2');\n"
            "%s}" % (family, style.group(1) if style else "normal", weight, name,
                     ("  unicode-range: %s;\n" % urange.group(1).strip()) if urange else ""))

    CSS_OUT.write_text(HEADER + "\n\n".join(faces) + "\n", encoding="utf-8")
    print("%d font files, %.0f KB -> %s" % (len(seen), total / 1024, OUT))


if __name__ == "__main__":
    main()
